### ISSUE TITLE
Can profiles refer to other profiles?

### ISSUE THREAD

**Issue by leekowalkowski-hmrc** [hmrc/service-manager#73]
Example: As a frontend developer, I would like to include "ACME_SERVICE_ALL" in my profile, so that I don't have to include "ACME_SERVICE", "ACME_SERVICE_PROXY", "ACME_SERVICE_STUBS" and keep it up-to-date.

I think it would be nice to have my frontend service refer to a dependent services profile if possible, instead of including all of the other services dependencies in my profile.

At the moment, if the other service profile changes, I need to check the profile of my frontend.

**Comment by jakobgrunig** [comment]
I’ve done some investigation. The reason we are not doing this is because it could case loops. PROFILE_A includes PROFILE_B that includes PROFILE_A. The complexity that would be required to add a protection to loops is not worth the effort in my opinion.
What you are looking for can be achieved with the wildcard *. For example: `ACME_*`
If you add that to your profile, all services starting with ACME_ will be included.

Leaving it open for now hoping for a PR at some point ;)
